'use client';
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from './components/Navbar.js'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <title>{children.title}</title>      */}
      </head>
      <body><Navbar></Navbar>{children}</body>
    </html>
  )
}
